# name字段是 workflow 的名称
name: Travel应用自动构建并发布到阿里云服务器
# on字段指定触发 workflow 的条件，通常是某些事件.除了代码库事件，GitHub Actions 也支持外部事件触发，或者定时运行。
on:
  #监听push操作
  push:
    # 可以限定分支或标签
    branches:
      # master分支，你也可以改成其他分支
      - master
# 表示要执行的一项或多项任务
jobs:
  # 每一项任务的job_id
  build:
    # name字段是任务的说明
    name: '打包构建并上传到服务器'
    # runs-on字段指定运行所需要的虚拟机环境。它是必填字段
    runs-on: ubuntu-latest
    # steps字段指定每个 Job 的运行步骤，可以包含一个或多个步骤
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.1"
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "travel" # 这是要复制到阿里云静态服务器的文件夹名称
          REMOTE_HOST: "47.97.231.9" # 你的阿里云公网地址
          REMOTE_USER: "root" # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: "/var/www/html/v19" # 打包后的 dist 文件夹将放在 /root/node-server
